version: '3.8'

services:
  ether-tx-parser:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ETH_PARSER_SERVER_PORT=8080
      - ETH_PARSER_ETHEREUM_RPC_URL=https://ethereum-rpc.publicnode.com
    volumes:
      - ./logs:/app/logs